### ISSUE TITLE
Issue with existing solution for bandit20->21 on new Docker setup

### ISSUE THREAD

**Issue by x56** [OverTheWireOrg/OverTheWire-website#45]
The existing solution at http://overthewire.org/wargames/bandit/bandit21.html suggests two logins to solve the level. (Presumably) due to network isolation between containers, this no longer works. The level is still solvable using multiple ttys in one SSH session or by backgrounding the listener process.

Either the network isolation issues should be addressed or the hint updated to reflect the new technique required to solve.

**Comment by avanpo** [comment]
This is still an issue. As far as I can tell, backgrounding the listener process won't work, since you need to read/write to it while the connection is open.

Screen isn't installed, but tmux is -- so that will work. The port forwarding technique described at http://overthewire.org/help/sshinfra.html also works.

**Comment by Rom1deTroyes** [comment]
screen is installed, but can't run :
```
bandit20@bandit:~$ screen
Directory  '/var/run/screen' must have mode 777. 
bandit20@bandit:~$ screen -v
Screen version 4.03.01 (GNU) 28-Jun-15
```

**Comment by Rom1deTroyes** [comment]
BTW, you don't need to use multiple connection to solve this level...
(severals solutions here !)

**Comment by Fieel** [comment]
I solved it using the hint and didn't even know what a docker was (TIL), so it's doable. It took some time though

**Comment by morla10111** [comment]
The level description has been updated. Please don't discuss level related stuff here.
