### ISSUE TITLE
bandit15 HEARTBEATING / Read R BLOCK explanation

### ISSUE THREAD

**Issue by Dietr1ch** [OverTheWireOrg/OverTheWire-website#50]
The helpful note solves the "HEARTBEATING" issue, but fails to explain what was the problem. It says to search a section ("CONNECTED COMMANDS") missing on the openssl manual.

**Comment by StevenVanAcker** [comment]
that section is not missing, it's most likely just not in the manpage you are looking at

**Comment by Dietr1ch** [comment]
Oh, thanks, I'll be more careful with the manpage reading. It is not on `man openssl`, but the information there was indeed enough.

**Comment by bozh** [comment]
@Dietr1ch 
You can find the **CONNECTED COMMANDS** section at [`man s_client`](https://man.cx/s_client#heading5).

**Comment by jeffbmartinez** [comment]
@Dietr1ch a couple years later... but I also had trouble finding any mention of the info needed to satisfy the *why* it worked :). `man s_server` got me a bit closer showing there are other commands than `R` and `Q`, but the one I expected to find wasn't included. I went through the source for s_server and found the reason: https://github.com/openssl/openssl/blob/master/apps/s_server.c#L2469

Using the `-tlsextdebug` flag shows that heartbeat is considered extension, so it makes some sense that it isn't included in the man page documentation.
