### ISSUE TITLE
L: 16->17 Nmap scan returns invalid response 

### ISSUE THREAD

**Issue by mariellefoster** [OverTheWireOrg/OverTheWire-website#51]
When you run an nmap scan with the flag -sV, the ports return with the information except for the correct port, which classifies its services as ssl/unknown, and prints out the message below. The correct port is therefore readily detectable because of this "error response."

bandit16@melinda:~$` nmap localhost -p 31000-32000 -sV

Starting Nmap 6.40 ( http://nmap.org ) at 2016-08-31 18:05 UTC
Nmap scan report for localhost (127.0.0.1)
Host is up (0.00052s latency).
Not shown: 996 closed ports
PORT      STATE SERVICE     VERSION
31046/tcp open  echo
31518/tcp open  ssl/echo
31691/tcp open  echo
31790/tcp open  ssl/unknown
31960/tcp open  echo
1 service unrecognized despite returning data. If you know the service/version, please submit the following fingerprint at http://www.insecure.org/cgi-bin/servicefp-submit.cgi :
SF-Port31790-TCP:V=6.40%T=SSL%I=7%D=8/31%Time=57C71C75%P=x86_64-pc-linux-g
SF:nu%r(GenericLines,31,"Wrong!\x20Please\x20enter\x20the\x20correct\x20cu
SF:rrent\x20password\n")%r(GetRequest,31,"Wrong!\x20Please\x20enter\x20the
SF:\x20correct\x20current\x20password\n")%r(HTTPOptions,31,"Wrong!\x20Plea
SF:se\x20enter\x20the\x20correct\x20current\x20password\n")%r(RTSPRequest,
SF:31,"Wrong!\x20Please\x20enter\x20the\x20correct\x20current\x20password\
SF:n")%r(Help,31,"Wrong!\x20Please\x20enter\x20the\x20correct\x20current\x
SF:20password\n")%r(SSLSessionReq,31,"Wrong!\x20Please\x20enter\x20the\x20
SF:correct\x20current\x20password\n")%r(Kerberos,31,"Wrong!\x20Please\x20e
SF:nter\x20the\x20correct\x20current\x20password\n")%r(FourOhFourRequest,3
SF:1,"Wrong!\x20Please\x20enter\x20the\x20correct\x20current\x20password\n
SF:")%r(LPDString,31,"Wrong!\x20Please\x20enter\x20the\x20correct\x20curre
SF:nt\x20password\n")%r(SIPOptions,31,"Wrong!\x20Please\x20enter\x20the\x2
SF:0correct\x20current\x20password\n");

Service detection performed. Please report any incorrect results at http://nmap.org/submit/ .

**Comment by StevenVanAcker** [comment]
well done! now please don't post spoilers
