### ISSUE TITLE
Connection to server failed

### ISSUE THREAD

**Issue by dannyboy1994** [OverTheWireOrg/OverTheWire-website#59]
The server seems offline. Try to connect using the command ssh bandit0@bandit.labs.overthewire.org but it doesn't work and retrieve the message: ssh: connect to host bandit.labs.overthewire.org port 22: Connection refused
Don't know what is up.

**Comment by StevenVanAcker** [comment]
OverTheWire switched to a new server setup. The bandit game now requires SSH to port 2220 instead of 22.

Please don't open support tickets for the games here, this repository is only for the website. For support on the games, we use IRC
