### ISSUE TITLE
Can cd into any level on any game and kinda cheat

### ISSUE THREAD

**Issue by n3gz404** [OverTheWireOrg/OverTheWire-website#60]
Hey guys, was wondering if you knew that as soon as you log in (at least I can from bandit1 login) can just do a cd .. and see every level's starting folder and get in and just register every level as "complete" on wechall. It kind of defeats the purpose of finding each password on each level. Not that im going to because that would ruin the experience i could gain from learning here but was just wondering if this was unrestricted on purpose?

**Comment by StevenVanAcker** [comment]
As a particular user, you only have access to your own password, not everyone else's. The wechall command does not care about which directory you are in, it has no more information about the passwords than your current user. Of course, if you happen to find a way to access all the passwords, then all the better for you :) Just try it out, that's what the environment is for.

Please don't open support tickets for the games here, this repository is only for the website. For support on the games, we use IRC.
