### ISSUE TITLE
Leviathan "wechall" command throws a ssl-related Error

### ISSUE THREAD

**Issue by roncapat** [OverTheWireOrg/OverTheWire-website#61]
Here is the output:

> Traceback (most recent call last):
  File "/usr/bin/wechall", line 33, in <module>
    ssl_sock.connect((host, port))
  File "/usr/lib/python3.4/ssl.py", line 864, in connect
    self._real_connect(addr, False)
  File "/usr/lib/python3.4/ssl.py", line 855, in _real_connect
    self.do_handshake()
  File "/usr/lib/python3.4/ssl.py", line 828, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)

**Comment by roncapat** [comment]
SOLVED: today it just works. 

PS: I noticed a change in the host identity while connecting through SSH.

**Comment by StevenVanAcker** [comment]
we have switched to a new server setup, which explains your problems. Please don't open support tickets for the games here, this repository is only for the website. For support on the games, we use IRC
