### ISSUE TITLE
Licensing information

### ISSUE THREAD

**Issue by massonpj** [OverTheWireOrg/OverTheWire-website#63]
Could not find licensing information on the site or in any repos here on Github. I'd expect to find a file in the root repo titled "License.md", "License.txt", "COPYING.txt" (typical for GPL licenses), or even a reference in the "README.md". 

I do find [two files](https://github.com/OverTheWireOrg/OverTheWire-website/search?utf8=%E2%9C%93&q=license&type=) with licensing information, but they are not original works by OverTheWireOrg.

You can find more information about how to license your work from Github here: https://help.github.com/articles/licensing-a-repository/

Although the site includes the "Fork me on Github" icon and link, without a license, by default (in the U.S. and many other jurisdictions), your works are, "All Rights Reserved" and thus not available to others without your permission. If you do indeed hope to find contributors and co-developers, I would suggest adding an OSI-Approved Open Source License, as Github recommends.

**Comment by StevenVanAcker** [comment]
thanks for the info! I usually don't deal with licenses and legal matters like that, but I will have a look at this in the near future as it may be helpful to others :)
