### ISSUE TITLE
Unable to connect

### ISSUE THREAD

**Issue by tommy-qiu** [OverTheWireOrg/OverTheWire-website#66]
![screen shot 2017-10-04 at 5 54 19 pm](https://user-images.githubusercontent.com/26195773/31201556-165153da-a92d-11e7-9d5b-234c4e6d52dd.png)

I've been unable to connect with SSH, I would much appreciate help.

**Comment by StevenVanAcker** [comment]
for support with the games, please use the #wargames channel on our IRC network. Issues with logging in occur from time to time, but it's best to report this via IRC so we can take care of them immediately
