### ISSUE TITLE
Level 20 requires password from level 14?

### ISSUE THREAD

**Issue by limick** [OverTheWireOrg/OverTheWire-website#68]
In level 20 we are asked to launch a process using `./suconnect`. As a result, a python script runs as bandit 15 and requires the password of bandit 14.

Output of `ps aux`:
`bandit15   730  0.1  0.0  30260  8720 ?        Ss   09:08   0:00 /usr/bin/python /usr/bin/sendnextpass.py /home/bandit15/.bandit14.password /etc/bandit_pass/bandit15`

That seems wrong. I would expect the process to be more like:
`/usr/bin/python /usr/bin/sendnextpass.py /home/bandit21/.bandit20.password /etc/bandit_pass/bandit21`

**Comment by StevenVanAcker** [comment]
you're misinterpreting running processes. For support, go to the IRC channel
