### ISSUE TITLE
Wrong Permissions level 6?

### ISSUE THREAD

**Issue by Jfarrington86** [OverTheWireOrg/OverTheWire-website#76]
Level Goal

The password for the next level is stored somewhere on the server and has all of the following properties:

    owned by user bandit7
    owned by group bandit6
    33 bytes in size

bandit5@bandit:/var/lib/dpkg/info$ cat bandit7.password 
cat: bandit7.password: Permission denied
bandit5@bandit:/var/lib/dpkg/info$ ls -ls bandit7.password 
4 -rw-r----- 1 bandit7 bandit6 33 Dec 28 14:34 bandit7.password

bandit5@bandit:/var/lib/dpkg/info$ groups bandit5
bandit5 : bandit5

User bandit5 does not appear to have read permissions for this file.

**Comment by morla10111** [comment]
This is the repository of the OTW website. It is NOT a help channel for the games. I ensure you the game is working as intended. Feel free to hop on the IRC to get assistance.
