### ISSUE TITLE
Wrong level field in the layout for bandit30 and bandit31

### ISSUE THREAD

**Issue by TeddyHartanto** [OverTheWireOrg/OverTheWire-website#84]
Hi, as mentioned in the title of this issue, there's a minor mistake in the level numbers. See the screenshots below:
![image](https://user-images.githubusercontent.com/11240927/43042132-c642ae24-8da7-11e8-97c1-d5d6628e79bf.png)
![image](https://user-images.githubusercontent.com/11240927/43042137-d52e6f9a-8da7-11e8-9520-872b87db250f.png)

**Comment by morla10111** [comment]
Hey,
thanks for reporting! Should be fixed now.
cheers,
morla
