### ISSUE TITLE
Bad Request when URL param contains hash symbol "#"

### ISSUE THREAD

**Issue by shinohara-rin** [OverTheWireOrg/OverTheWire-website#86]
request "http://natas11.natas.labs.overthewire.org/?bgcolor=%23ffffff" and I got 400

![screenshot_20180803_213051](https://user-images.githubusercontent.com/25588514/43645480-9d40b00e-9764-11e8-9e82-7a54eb2d20cd.png)

was that on purpose?

**Comment by morla10111** [comment]
Hey,
thank you for reaching out. This is not the bug tracker of the overthewire.org wargames. Please report any issues with the games via irc to irc.overthewire.org #wargames. Thank you.

I cant be able to recreate the error. Maybe just hickups?

Cheers,
morla
