### ISSUE TITLE
Challenge 24

### ISSUE THREAD

**Issue by ikbenlike** [OverTheWireOrg/OverTheWire-website#87]
Challenge 24 doesn't seem to work. I followed two guides after independently trying to figure it out, but none of the solutions have worked as of yet. The script in /var/spool/bandit24 just doesn't seem to execute at all.

**Comment by Rom1deTroyes** [comment]
No problem for me : cron job are executed at the time they must be done...
If you need assistance, try the irc chan (-:

**Comment by morla10111** [comment]
This is not the bug tracker for the overthewire.org wargames. Please report any issues you are having with the games on the IRC channel #wargames at irc.overthewire.org. Thank you!
