### ISSUE TITLE
Website doesn't redirect to https

### ISSUE THREAD

**Issue by dnperfors** [OverTheWireOrg/OverTheWire-website#88]
Hi,

Nowadays it is pretty common to go to https websites by default, however overthewire.net goes to http, making it vulnerable for man in the middle attacks. I know there is only static content on there, but even that content could be changed or extra scripts could be injected in order to steal data from users.

Please redirect to https from the http site.

**Comment by morla10111** [comment]
Hello @dnperfors,
thanks for reaching out.
Redirecting from http to https does not help with a MITM sittuation, as the MITM could simply change the redirect so it does not go to https. I am not going to obscure this fact by implementing a redirect.
As you said in your first sentence, it should be common to connect to the https endpoint by default. This should be done by the user (typing `https://`) or by a brower setting or plugin.

Regards,
morla
