### ISSUE TITLE
Password for vortex0 is changed.

### ISSUE THREAD

**Issue by mohamedotnet** [OverTheWireOrg/OverTheWire-website#90]
When solving vortex 0, the server sends the username and the password.
Unfortunately the password doesn't work.

**Comment by morla10111** [comment]
Hello there,
this is not the support channel for the overthewire.org wargames. Its the issue tracker for the website.
If you need support, please come and join us on irc.overthewire.org #wargames.

Anyway, I can assure you that the level works as it should.

Cheers,
morla
