### ISSUE TITLE
Any possibility of getting an .ova of an overthewire bandit server?

### ISSUE THREAD

**Issue by thehookup** [OverTheWireOrg/OverTheWire-website#91]
My school's computer lab has basically every outgoing port blocked (other than port 80).  I'd love to be able to host overthewire locally on VirtualBox and then have my students connect to that IP locally to be able to do the simulations.

The problem is that I'm not savvy enough to take the github files here and set up the docker infrastructure to get it going.  I would be really grateful if someone could post a small guide or even better just upload a pre-built .ova that I could load up.  Thanks!

**Comment by morla10111** [comment]
hey there,
i am afraid that the bandit game is not available for download. maybe your students could use a web based ssh client to connect to the games? or the it department could allow outgoing ssh connections just to the bandit host/port?

cheers,
morla
