### ISSUE TITLE
Krypton level 6 missing README2

### ISSUE THREAD

**Issue by Psimage** [OverTheWireOrg/OverTheWire-website#93]
From the description on the website:
> (NOTE - it is possible though. Using plain language as a one time pad key has a weakness. As a secondary challenge, open README2)

There is no README2.
The README file in the game directory also has this line, but slightly different:

> (NOTE - it is possible though.  Using plain language as a one time pad
> key has a weakness.  As a secondary challenge, open README in that directory)

**Comment by StevenVanAcker** [comment]
thanks for pointing this out, I have no idea where this file went, so I have removed the reference to it
